name: Docker Image Build and Run

on:
  push:
    branches: [ Pushing-Cloned-Code ]
    tags: ["*"]
    paths:
      - '**'
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Image from Dockerfile
      run: docker build . --file Dockerfile --tag assignment
    - name: Run the Docker Image for expected output
      run: docker run assignment